### ISSUE TITLE
Exception while trying to convert image

### ISSUE THREAD

**Issue by stefancvetkovic** [DavidAnson/ConvertTo-Jpeg#12]
Hi,
Im getting following error:
```
dir : System.Management.Automation.MethodInvocationException: Exception calling "Wait" with "0" argument(s): "One or more errors occurred." ---> System.AggregateException: One or more errors occurred. ---> System.Exception: No suitable transform
was found to encode or decode the content. (Exception from HRESULT: 0xC00D5212)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at CallSite.Target(Closure , CallSite , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at <ScriptBlock><Process>(Closure , FunctionContext )
```

thanks

**Comment by DavidAnson** [comment]
It sounds like maybe you don't have the necessary codecs installed. See https://github.com/DavidAnson/ConvertTo-Jpeg#heicheif

If you can't open the source image in the Windows Photo app, this tool is unlikely to work.
